name: Dev Deployment

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.8-eclipse-temurin-21
    env:
      SERVER_HOST: "165.22.220.122"
      DEPLOY_DIR: "/var/www/"
      JAR_FILE: "logcheck-0.0.1-SNAPSHOT.jar"
      SERVER_USER: "root"
      JAVA_CMD: "java -jar"

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: mvn clean install
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
      - name: Deploy to Dev
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/$JAR_FILE $SERVER_USER@$SERVER_HOST:$DEPLOY_DIR/
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST "nohup $JAVA_CMD $DEPLOY_DIR/$JAR_FILE --server.port=8081 > $DEPLOY_DIR/app.log 2>&1 &"
