stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.8.8-eclipse-temurin-21
  script:
    - mvn clean package
    - ls -l target
  artifacts:
    paths:
      - target/travel-app-0.0.1-SNAPSHOT.jar
  rules:
    - changes:
        - src/java21/**

deploy:
  stage: deploy
  image: eclipse-temurin:21-jre-alpine
  variables:
    DEPLOY_DIR: "/var/www/html/"
    JAR_FILE: "travel-app-0.0.1-SNAPSHOT.jar"
    SERVER_USER: "root"
    SERVER_HOST: "143.110.251.96"
    JAVA_CMD: "java -jar"
    SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
    - scp target/$JAR_FILE $SERVER_USER@$SERVER_HOST:$DEPLOY_DIR
    - |
      ssh $SERVER_USER@$SERVER_HOST <<EOF
      pkill -f $JAR_FILE || true
      nohup $JAVA_CMD $DEPLOY_DIR/$JAR_FILE --server.port=8081 > $DEPLOY_DIR/app.log 2>&1 &
      EOF
  rules:
    - changes:
        - src/java21/**
