name: Java CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_DIR: "/var/www/html/"
      JAR_FILE: "logcheck-0.0.1-SNAPSHOT.jar"
      SERVER_USER: "root"
      SERVER_HOST: "64.227.145.190"
      JAVA_CMD: "java -jar"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client lsof

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          echo "SSH setup complete."

      - name: Stop Existing Application (If Running)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST <<EOF
          if command -v lsof &> /dev/null && lsof -t -i:8081 > /dev/null; then
            echo "Stopping application on port 8081..."
            kill -9 \$(lsof -t -i:8081)
          else
            echo "No application running on port 8081."
          fi
          rm -rf $DEPLOY_DIR/*
          mkdir -p $DEPLOY_DIR
          EOF

      - name: Upload JAR to Server
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $JAR_FILE $SERVER_USER@$SERVER_HOST:"$DEPLOY_DIR/"

      - name: Start Application
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST <<EOF
          nohup $JAVA_CMD $DEPLOY_DIR/$JAR_FILE --server.port=8081 > $DEPLOY_DIR/app.log 2>&1 &
          echo "Application successfully started on port 8081."
          EOF
